Serve static files at Django root
azavea/echo-locator pull request #454
Opened 2022-04-15 12:35 UTC by rachelekm

## Overview

We are currently using `django-spa` and a `mastarm` proxy on `start` to serve static files, however these static files were previously inaccessible to `django-spa`. This mounts the static assets created through `mastarm` to the django `/static` folder, allowing `django-spa` to find `index.html` on call to `/`.

### Notes

- The `index.html` file is not generated as part of the `mastarm` bundler and needed to be separately copied in, which is unideal. Ultimately, this serves as a temporary fix until we can move forward with a different bundler in #376.

## Testing Instructions

 * `scripts/update`
 * `scripts/server`
 * Navigate to `http://localhost:8085/` and confirm static page loads

Resolves #424

2022-04-18 13:03 UTC, ktohalloran requested changes
I learned a lot about Docker volumes from reviewing this so thanks for adding me as a reviewer! As you can see from my comments, I wasn't able to get it to run as is; however, this was a tricky one trying to work around `mastarm` and the frontend and backend not sharing a root the same way they do in other projects, so good job isolating and addressing the issue on this one!

2022-04-18 13:03 UTC, ktohalloran commented on docker-compose.yml
> +      - ./taui/assets:/usr/local/src/backend/static/assets
```suggestion
      - ./taui/assets:/usr/local/src/backend/static/assets
      - ./taui/index.html:/usr/local/src/backend/static/index.html
```

Unfortunately, copying `index.html` as a command didn't work for me; however, mounting it as its own volume did. I'm not sure whether this is best practice but it makes sense to me that this file could persist across Docker containers like the rest of the stuff in `taui/assets`.

2022-04-18 13:03 UTC, ktohalloran commented on docker-compose.yml
> +      - "cp ./taui/index.html /usr/local/src/backend/static"
```suggestion
```
If mounting `index.html` as its own volume works, this is no longer necessary.

2022-04-19 12:55 UTC, rachelekm commented on docker-compose.yml
> +      - ./taui/assets:/usr/local/src/backend/static/assets
I'm thinking I must have already had the `index.html` file in my `/static` folder after trying to mount from before, so it was able to work for me locally but not actually in practice. This way makes sense to me and works well, so just pushed that change!

2022-04-26 11:07 UTC, ktohalloran approved these changes
Looks good! 👍

2022-04-26 20:12 UTC, maurizi approved these changes

2022-04-27 13:27 UTC, merged