Fix adding addresses in anonymous mode
azavea/echo-locator pull request #527
Opened 2022-05-23 23:24 UTC by rachelekm

## Overview

This PR adjusts updating `userProfile` when adding destinations so that the destination fields no longer disappear when trying to add more than one in anonymous mode. In addition, I noticed that after selecting a new primary destination, sometimes the origin on the main page updated but not the "from" field in the sidebar. I created a issue #525  for it and resolved it here, as well.

### Checklist

- [ ] Run `./scripts/format` to lint, format, and fix the application source code.

### Notes

- I noticed if I had more than one destination with the same type of purpose (multiple "work" destinations, for example) the "from" address on the main page sidebar would not update and I could not select a different destination address. The `value` for the `Select` component was set to the destination's `purpose`, which wouldn't update because the `value` wasn't unique between these selections. Instead, I set the `destination` obj itself to `value` to resolve this issue.

## Testing Instructions

 * `scripts/server`
 * Login to the site as an anonymous user
 * Confirm you can add more than one address to profile and it persists until logout
 * Update primary address to new address and confirm the "from" field on the main page sidebar updates
 * Confirm you can select a different address in the "from" selection and app updates

Resolves #521 , #525

2022-05-25 14:13 UTC, ddohler requested changes
This works but it seems to introduce a change in the way the `from:` menu behaves after saving the user's profile.

On `develop`, after saving the user's profile, the primary destination is displayed with its Purpose prefix:
<img width="403" alt="Screen Shot 2022-05-25 at 10 07 12" src="https://user-images.githubusercontent.com/447977/170282188-35ab3c52-37d3-4d15-bcd0-e67924ad8838.png">

But on this branch, after saving the profile, the primary address is missing the purpose prefix:
<img width="411" alt="Screen Shot 2022-05-25 at 10 06 55" src="https://user-images.githubusercontent.com/447977/170282277-980f9a94-461f-48b1-ad43-c4576a3be692.png">

Changing the dropdown to something else does work, and the prefix is displayed after doing so. I think we need to be using something different as the value, either the destination's index within the destination array, or its full `${purpose}: ${label}` string.

2022-05-25 20:40 UTC, rachelekm commented
Uh oh, the dropdown options showed the purpose and I totally missed that the actual value didn't include it. To keep the 'prefix: address' label consistent and translatable, I ended up pulling out the labelling logic from the `locationsWithLabels` fn into a separate `labelDestination` fn to call for the Select value, too.

2022-05-26 13:28 UTC, ddohler commented
Hmm, so translation and the labeling work correctly now, but now it seems like we're maybe back to where we started because if I give two or more destinations the same purpose, I can only select one of them, which I think is the issue that motivated #525 in the first place? If this seems like it's going to blow up in complexity, we could potentially kick #525 back to To-Do (and increase its estimate) and just merge the address-adding fixes here.

2022-05-26 13:59 UTC, rachelekm commented
Oh interesting, thank you for catching this. If I give two or more destinations with the same purpose, the "from" updates to the new primary destination and I'm able to select the other destination with a mouse but not through arrow keys and the label includes the purpose twice for me: 
![bha_issue_525_example](https://user-images.githubusercontent.com/36374797/170502120-0ea444a6-21e0-42c6-ae2d-ba057a74a2a6.gif)

I agree this is less of a one-line simple fix than I thought at the beginning so I'll undo my last two commits related to solving 525, adjusting 525 as you just described, and just merge the address-adding fixes here.

2022-05-26 14:02 UTC, ddohler commented
Oh that's interesting! I didn't realize you could actually click on it--I just noticed that the highlight doesn't move over it and assumed that meant that clicking wouldn't work, but apparently it does. So lots going on with this issue 🙂 -- I agree that working on it separately is the right move.

2022-05-26 14:08 UTC, rachelekm commented
Alas, I forgot to test with arrow keys! I'll be sure to update the issue to note the highlight isn't adjusting to the new destination value as part of selecting a new option, too. Thanks!

2022-05-26 14:42 UTC, ddohler approved these changes

2022-05-26 14:50 UTC, merged